### ISSUE TITLE
Stray CR character after replace_modified_part command

### ISSUE THREAD

**Issue by markusgritsch** [gornostal/Modific#96] opened 2015-08-19 10:19 UTC
Unmodified file:
![1](https://cloud.githubusercontent.com/assets/2684183/9353866/0ed5f55a-466c-11e5-8224-a2355113847a.png)

Deleting a line and saving the file:
![2](https://cloud.githubusercontent.com/assets/2684183/9353882/2253003c-466c-11e5-95a1-a408fc5c7784.png)

Invoking the command replace_modified_part:
![3](https://cloud.githubusercontent.com/assets/2684183/9353891/2ddc7fe6-466c-11e5-8760-c22ac0a8ccee.png)

Note the spurious CR appearing at the end of the reverted line.

I am using Git for Windows 2.5.  Changing "default_line_ending" has no effect.

Git settings, but seems to also have no effect:
core.autocrlf = true

**Comment by gornostal** [comment] 2015-08-29 14:51
@markusgritsch, can you create a [gist](https://gist.github.com) with a file (or a part of it), where you see the issue?
Also, please provide your git version.

Thanks.

**Comment by markusgritsch** [comment] 2015-08-29 18:40
I already mentioned that I use [Git for Windows 2.5] (https://git-for-windows.github.io/). However, I also had the same behaviour with previous versions of Git.

I think the crucial thing to reproduce the bug is to have a file which is in the repository with Unix (LF) line endings which gets checked out on Windows with Windows (CR LF) line endigs.  For example this file
https://github.com/nodemcu/nodemcu-firmware/blob/master/Makefile
has LF line endings in the repo (https://github.com/nodemcu/nodemcu-firmware/raw/master/Makefile) but my local clone of this file has CR LF line endings.

So here is an example with exactly that file:
![1](https://cloud.githubusercontent.com/assets/2684183/9563716/d1a28570-4e8d-11e5-8f56-470674999f38.png)

Now, if I delete line 3
![2](https://cloud.githubusercontent.com/assets/2684183/9563717/e1cfe938-4e8d-11e5-971d-655158702b93.png)

And then press CTRL+ALT+R
![3](https://cloud.githubusercontent.com/assets/2684183/9563723/f6bce4f4-4e8d-11e5-848a-a2a2cc251343.png)

the spurious CR appears.

Thanks for looking into this.

**Comment by gornostal** [comment] 2015-08-29 18:54
Hehe, I was wondering what is Window 2.5.
I think I know how to fix it. I'll create a fix, then you verify it, because I don't have access to Windows machine right now.

**Comment by markusgritsch** [comment] 2015-08-29 19:00
Great, looking forward to it.

**Comment by gornostal** [comment] 2015-08-29 19:09
I just pushed commit to master.

**Comment by markusgritsch** [comment] 2015-08-29 19:29
No, this does not change anything. Note, even if I change join_lines() to return "", a spurious CR appears (of course without any text from the original line):

![3](https://cloud.githubusercontent.com/assets/2684183/9563926/ef1f6300-4e94-11e5-9ea0-a35de44ea01b.png)

**Comment by gornostal** [comment] 2015-08-29 19:32
Made another fix. Hope that helps.

**Comment by markusgritsch** [comment] 2015-08-30 05:36
Unfortunately, still the same.

**Comment by gornostal** [comment] 2015-08-30 06:07
I just made another fix. And I'm pretty sure it will work.

**Comment by markusgritsch** [comment] 2015-08-30 06:35
Still no change. If it helps, when doing
```git diff Makefile > tmp.diff```
the file tmp.diff has Unix (LF) line endings.

**Comment by gornostal** [comment] 2015-08-30 06:40
OK. I'll get back to this when I get access to a Windows machine.

**Comment by markusgritsch** [comment] 2015-08-30 06:41
All right.

**Comment by markusgritsch** [comment] 2015-11-30 11:43
Hi gornostal, any chance you will take another look into this issue?

**Comment by gornostal** [comment] 2015-11-30 11:49
Sorry for the delay.
I'll try to find time for this today or tomorrow.

Thanks for the reminder!

**Comment by gornostal** [comment] 2015-12-01 17:56
Could not reproduce the bug today.

Here is what I did:

1. downloaded and installed Git-2.6.3-64.bit.exe on Windows 7
1. downloaded and installed ST 3
1. `git config --global core.autocrlf true`
1. `git checkout https://github.com/nodemcu/nodemcu-firmware`
1. modified a few lines in [Makefile](https://github.com/nodemcu/nodemcu-firmware/blob/master/Makefile)
1. pressed `Ctrl+Alt+R`
1. Modific reverted lines just fine, no CR symbols in the end of the line

**Comment by markusgritsch** [comment] 2015-12-02 07:06
Did you *delete* some lines in the Makefile so that they were added back when pressing Ctrl+Alt+R?

Reverting works fine with modified lines and added lines.  The problem appears only when deleting lines from the original file.

**Comment by gornostal** [comment] 2015-12-02 07:09
Oh.. I missed that in your description. Will try again today.

**Comment by markusgritsch** [comment] 2015-12-04 18:30
Have you been able to reproduce it?

**Comment by gornostal** [comment] 2015-12-04 18:32
Not yet. Got distracted at work that day.
Downloading virtual box...

**Comment by gornostal** [comment] 2015-12-04 20:46
I reproduced it and here is what I found out:

CR appears only if I use `\r\n` to join the lines.
When I change it to `\n`, it joins them just fine.

Can you find the line with `"\r\n"` in Modific.py and change that to \n, then let me know if it works for you?

If it does I will simply add a new config option to manually change line endings, because as it turns out, we cannot use windows line endings on windows in some cases like yours.

**Comment by gornostal** [comment] 2015-12-05 08:13
Checked in changes to `issue-96` branch.
Will merge when @markusgritsch confirms it's working.

**Comment by markusgritsch** [comment] 2015-12-05 20:21
Yes, this seems to solve the issue, thanks!

But why add a "line_ending" configuration option?  Who would need to set this to something else than \n?

**Comment by gornostal** [comment] 2015-12-05 20:28
It's good to hear it works.

I thought I could break the functionality for someone who needs \r\n, but maybe you are right. I'll use \n.

P.S. Thanks for being insistent :)

**Closed** 2015-12-05 20:31 UTC
Labels: bug

**Comment by markusgritsch** [comment] 2015-12-05 20:45
You are welcome ;)  I like Modific a lot, and this was the only outstanding issue I had with it.  Great that it's fixed now.

Concerning the config option: I think, it is unnecessary.  Mind you: The problem with the stray \r characters appeard on a file, which had Windows (\r\n) line endings, and even there the config option has to be set to \n.
